### ISSUE TITLE
bug in constructor when passing column mapped arguments

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#210]
When trying to cast a dataframe that looks like

```
scenario    iso    year    Under $1.9/day    Under $3.2/day    Under $5.5/day

0    SSP1    ABW    2010    60461.658417    81761.798605    96589.505255

1    SSP1    ABW    2015    55879.582348    81353.923882    101384.564016

2    SSP1    ABW    2020    47184.128841    74791.821442    99462.941162

3    SSP1    ABW    2025    35996.982744    64023.327405    93332.212043

4    SSP1    ABW    2030    23439.708278    48772.959049    80962.660882
```

I get a value error with the following code:

```
y = pyam.IamDataFrame(vf, value=cols, model='SSP Data', region='iso', unit='baz')
```

But this works as expected:
```
x = pyam.IamDataFrame(vf.rename(columns={'iso': 'region'}), value=cols, model='SSP Data', unit='baz')
```
Should probably be addressed with #208

**Comment by danielhuppmann** [comment]
@gidden, I added a unit test (see https://github.com/danielhuppmann/pyam/commit/bc1c5c46e7b8df97b965ebd5c5344691211ec316), but I don't get a `ValueError`. Instead, I get unexpected behaviour where the `region` column is all `iso` rather than the values of the `iso` column. In the original data where you encountered the bug, did you have multiple regions and was the `ValueError` something about non-unique data?
