### ISSUE TITLE
suggest conda for windows installation

### ISSUE THREAD

**Issue by maxtav** [IAMconsortium/pyam#362]
ciao
I have had difficulties installing pyam via pip (matplotlib and gnuwin packages).
Daniel suggested to do it via conda and it worked smoothly. Probably worth recommending it for new users.

**Comment by danielhuppmann** [comment]
Thanks @maxtav for persevering with the installation in spite of troubles!

I'll close this issues (because there is nothing for us to really do) but your comment will still be available to any user searching our [issues](https://github.com/IAMconsortium/pyam/issues?q=is%3Aissue) for keywords like "Windows install" - and so they can follow your recommendation!
