### ISSUE TITLE
Recursive aggregation of variables

### ISSUE THREAD

**Issue by tburandt** [IAMconsortium/pyam#385]
Hi all, firstly, thanks for the amazing work with this package. A loots of features are really good to use and well documented. However, we still face the issue that with multiple levels in a variable, the manual aggregation of these becomes quite tedious.

Example:
`Secondary Energy|Electricity|Wind|Onshore` and `Secondary Energy|Electricity|Wind|Offshore` can be successfully aggregated with `iDataFrame.aggregate(variable='Secondary Energy|Electricity|Wind', append=True)`

However, when calling the aggregate function one level higher (e.g., `iDataFrame.aggregate(variable='Secondary Energy|Electricity', append=True)` without prior aggregation of the wind|onshore and wind|offshore variables to a combined wind variable, the values for onshore and offshore wind are omitted. Doing this aggregation with several variables and multiple levels each might lead to errors when presenting the aggregated variables.

Therefore, I think that an additional function handling a recursive/nested aggregation of variables would be really helpful. Such that you could call just `aggregate(variable='Secondary Energy|*')` und all levels below that variable would be subsequently aggregated.

**Comment by danielhuppmann** [comment]
Thanks @tburandt for this suggestion! This would definitely be really useful.

I'd suggest to add a keyword-argument `recursive` to the function, so that you can call it like
`aggregate(variable='Secondary Energy|Electricity', recursive=True, append=True)`.

See the snippet below for a simple implementation of your request, which I did a while ago - it would be great if you could give it a try to implement this feature (and a related test) as an "out-of-the-box" feature. 

```
for d in reversed(range(1, max(pyam.find_depth(df.data.variable)) + 1)):
    depth = pyam.find_depth(df.data.variable)
    var_list = df.data.variable[[i==d for i in depth]].unique()
    vars_up = pd.Series([pyam.reduce_hierarchy(i, -1) for i in var_list]).unique()
    for v in vars_up:
        df.aggregate(v, append=True)
```

Happy to assist if you take the lead!

**Comment by tburandt** [comment]
Thanks for appreciating the usefulness :) 
and yes I'm happy to work on this!

**Comment by danielhuppmann** [comment]
closing as implemented
