### ISSUE TITLE
`set_meta` is backwards

### ISSUE THREAD

**Issue by znicholls** [IAMconsortium/pyam#417]
Standard python syntax for setting values in dictionaries is `dict[key] = value`. pyam's `set_meta` instead uses `set_meta(value, key)`. Am I the only one who finds this backwards or is this something that could be changed in an (API-breaking) version in future?

**Comment by znicholls** [comment]
@danielhuppmann thoughts?

**Comment by danielhuppmann** [comment]
Three answers:
1. I never thought of this as a dictionary (because it's about columns in a dataframe). That's why the arguments are actually called `value` and (column) `name`.
2. The `name` arg is optional because if `value` is a named series, the series name is used, so changing the order is problematic.
3. Rather than changing the API of `set_meta()`, I would rather suggest to add a new (additional) setter-method
    ```
    df[name] = value
   ```
   where `value` can be a str, number, list of correct length, or (indexed) series.

**Comment by znicholls** [comment]
Nice nice nice

**Comment by danielhuppmann** [comment]
Closing as no further comment for almost a year.
